### ISSUE TITLE
Demo does not load Sample Data on Android

### ISSUE THREAD

**Issue by jdar** [couchbase-examples/flutter_cbl_learning_path#1]
Thank you for the complete-looking sample application. The work that was put into this shows.

Issue:
When the application is loaded on Android, the data for the sample application is incomplete or insufficient. 

Preliminary guess: I believe that loading the 'Sample Data' is failing half-way through import. Or something. (See log message below about trying to copy db to a folder.)

Steps to replicate (simplest):
- After logging in as 'demo@example.com' I see the Home page.
- Click '+' icon (bottom right)
- Click 'Select Warehouse'
- Enter something into 'City' input
- Click 'Search' button

Expected:
 I would expect to see options for warehouses which contain the search term

Actual:
     On Android: "No warehouses found matching criteria." 
    On iPhone:  correctly shows list of warehouses

Other things I tried:
  I tried to re-generate seed data in the database. (Menu => Developer => Load Sample Data. See "New Data Generated!" ... no change. The following was found in the logs:

I/flutter ( 5162): 2022-12-20 19:50:25.587352 [DatabaseProvider] info: initializing databases
I/flutter ( 5162): 19:50:26.956451| [DB] info: Copying prebuilt database from /data/user/0/com.example.flutter_cbl_learning_path/app_flutter/databases/startingWarehouses.cblite2 to /data/user/0/com.example.flutter_cbl_learning_path/app_flutter/databases/warehouse.cblite2
I/flutter ( 5162): 2022-12-20 19:50:27.185622 [DatabaseProvider] error: DatabaseException(errno 21: Couldn't copy file from /data/user/0/com.example.flutter_cbl_learning_path/app_flutter/databases/startingWarehouses.cblite2 to /data/user/0/com.example.flutter_cbl_learning_path/app_flutter/databases/.cblite/sTQ7u9/: Is a directory, code: unexpectedError)

Versions and additional system information:
Android (11 and 12)
OSX
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.4 21F79 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.73.1)

Other notes:
1) I am able to set my username. It persists across restarts. So, the database seems to be working
2) Another instance where seed data is missing is (Project -> Audit Editor -> Select Stock Item). as with Warehouses, the problem only occurs on Android; on my iPhone the data is available to search.

**Comment by jdar** [comment]
Oh -- I was testing on Android devices (11 and 12)

**Comment by biozal** [comment]
@jdar - I'll look into this in the morning.  The sample database loads both the stock items and warehouses.  If it doesn't load, neither dataset would be available.  I know I tested this on my pixel phone at one time that was running Android 12, but the info you provided is extremely helpful and I'll see if I can reproduce and get a patch in quickly.

**Comment by blaugold** [comment]
The error you are seeing has been fixed in the latest release of `cbl` (2.1.3). You will have to clear the app data to get it to reinitialize with the data from the prebuilt database.

Actually, Menu => Developer => Load Sample Data should also work after updating.

**Comment by jdar** [comment]
Tested. Works! Tested on Android 12.

However, I have noticed a new unrelated bug, while testing (That I did not observe before, but must have been present. Perhaps. I think.). 
I have opened the new bug on: #4
