### ISSUE TITLE
Cursor moves to start of input on build

### ISSUE THREAD

**Issue by jdar** [couchbase-examples/flutter_cbl_learning_path#6]
The stateless input widgets have a problem, when typing. Cursor moves to index 0 after every keystroke

IS THIS A PROBLEM:
Probably not, because this is a demo codebase. I get the sense that you have a different way of doing this, for your real codebase.

WHERE:
 on the 'Update User Profile' modal (First Name, Last Name, and Job Title)

Suggested quickfix, for demo purposes: 

Change 
`controller: TextEditingController(text: state.firstName),`
        
To:
`controller: TextEditingController()
                ..text = state.firstName
                ..selection =
                    TextSelection.collapsed(offset: state.firstName.length),
            `
            
           I will submit a PR shortly.

**Comment by biozal** [comment]
Resolved by PR
