### ISSUE TITLE
Not clear how to get replication working with Capella

### ISSUE THREAD

**Issue by PaulCapestany** [couchbase-examples/flutter_cbl_learning_path#9]
First off, thanks for putting this together @biozal (and @blaugold for cbl-dart)! 

I've been following the tutorial at [Set up Couchbase Capella and App Services for Audit Inventory Demo App](https://developer.couchbase.com/app-services-lp-audit-inventory?learningPath=learn/flutter-dart-sdk-app-services) (and went through all the prior tutorial steps as well), however, when running the iOS version of the demo app from this repo I cannot get it connect to Capella for replication.

I made sure to follow the `NOTE` directions in [replicator_providor.dart](https://github.com/couchbase-examples/flutter_cbl_learning_path/blob/38483d2f05c987c0f5c68a6bb143cdc8387f102a/src/lib/features/database/replicator_provider.dart#L20-L60) as well as at [route_bloc.dart](https://github.com/couchbase-examples/flutter_cbl_learning_path/blob/38483d2f05c987c0f5c68a6bb143cdc8387f102a/src/lib/features/router/bloc/route_bloc.dart#L103-L107). I then realized there was still no connection even being attempted unless I removed [`&& replicator.isClosed`](https://github.com/couchbase-examples/flutter_cbl_learning_path/blob/38483d2f05c987c0f5c68a6bb143cdc8387f102a/src/lib/features/database/replicator_provider.dart#L95). Then and only then did I get connection attempts (that failed), with the following logs from Xcode:

> flutter: 2024-02-07 14:48:00.507772 [ReplicatorProvider] info: starting replicator.
flutter: 14:48:00.517861| [Sync] info: {C4Replicator#11}==> litecore::C4RemoteReplicator 0x10213a4c8 @0x10213a4c8
flutter: 14:48:00.518383| [Sync] verbose: {C4Replicator#11} Replicator not yet created, saving progress level value for later...
flutter: 14:48:00.518896| [DB] info: {DB#12}==> litecore::SQLiteDataFile /Users/pac/Library/Developer/CoreSimulator/Devices/EC32A3E9-BB32-4EF5-9AB8-A2A7ADC1DF20/data/Containers/Data/Application/97611C23-DE19-46ED-B282-33A5F201B7B6/Documents/databases/team1_inventory.cblite2/db.sqlite3 @0x104b5c3f0
flutter: 14:48:00.519074| [DB] info: {DB#12} Opening database
flutter: 14:48:00.519489| [DB] info: {CollectionImpl#13}==> litecore::CollectionImpl team1_inventory/_default @0x60000294c3b0
flutter: 14:48:00.519662| [DB] info: {CollectionImpl#13} Instantiated
flutter: 14:48:00.520406| [DB] verbose: {DB#12} Next expiration time is 0
flutter: 14:48:00.520611| [Sync] info: {Repl#14}==> litecore::repl::Replicator /Users/pac/Library/Developer/CoreSimulator/Devices/EC32A3E9-BB32-4EF5-9AB8-A2A7ADC1DF20/data/Containers/Data/Application/97611C23-DE19-46ED-B282-33A5F201B7B6/Documents/databases/team1_inventory.cblite2/ ->ws://5tqvXXXXs0k.apps.cloud.couchbase.com:4984/projects/_blipsync @0x10258db00
flutter: 14:48:00.520807| [Sync] info: {Repl#14} Push=continuous, Pull=continuous, Options={{auth:{password:"********", type:"Basic", username:"demo@example.com"}, heartbeat:60, pinnedCert:"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUdzekNDQlp1Z0F3SUJBZ0lKQU1tYmRubk4vOHhnTUEwR0NTcUdTSWIzRFFFQkN3VUXXXXRmtaSGt1WTI5dEwzSmwKY0c5emFYUnZjbmt2WjJScFp6SXVZM0owTUI4R0ExVWRJd1FZTUJhQUZFREN2U2VPekRTRE1LSXoxL3Rzcy9DMApMSURPTUQ4R0ExVWRFUVE0TURhQ0dpb3VZWEJ3Y3k1amJHOTFaQzVqYjNWamFHSmhjMlV1WTI5dGdoaGhjSEJ6CkxtTnNiM1ZrTG1OdmRXTm9ZbUZ6WlM1amIyMHdI
flutter: 14:48:00.541784| [Sync] verbose: {C4Replicator#11} C4RemoteRepl 0x10213a4c8 created Repl 0x10258db00
flutter: 14:48:00.542335| [Sync] verbose: {Repl#14} Set progress notification level to 1
flutter: 14:48:00.542513| [Sync] info: {C4Replicator#11} Starting Replicator {Repl#14}
flutter: 14:48:00.542670| [Query] verbose: RecordEnumerator 0x60000350a688: (default, 110 0)
flutter: 2024-02-07 14:48:00.542871 [ReplicatorProvider] info: started replicator.
flutter: 14:48:00.543057| [WS] info: {BuiltInWebSocket#15}==> litecore::websocket::BuiltInWebSocket ws://5tqvXXXXs0k.apps.cloud.couchbase.com:4984/projects/_blipsync @0x104b90078
flutter: 14:48:00.559951| [WS] info: {BuiltInWebSocket#15} Connecting...
flutter: 14:48:00.560399| [Sync] info: {Repl#14} Scanning for pre-existing conflicts...
flutter: 14:48:00.560581| [Sync] info: {Repl#14} Found 0 conflicted docs in 0.000 sec
flutter: 14:48:00.560766| [Sync] verbose: {Repl#14} Remote-DB ID 1 found for target <ws://5tqvXXXXs0k.apps.cloud.couchbase.com:4984/projects/_blipsync>
flutter: 14:48:00.560934| [Sync] info: {Repl#14} No local checkpoint 'cp-CAa0SbeS6914fcDzw1lM9b22S/Y='
flutter: 14:48:00.749263| [WS] verbose: Sending request to ws://5tqvXXXXs0k.apps.cloud.couchbase.com:4984/projects/_blipsync:
	GET /projects/_blipsync HTTP/1.1
	Host: 5tqvXXXXs0k.apps.cloud.couchbase.com:4984
	Connection: Upgrade
	Upgrade: websocket
	Sec-WebSocket-Version: 13
	Sec-WebSocket-Key: mGnjS1XZcjs7AJL6tj0Gtw==
	Sec-WebSocket-Protocol: BLIP_3+CBMobile_3,BLIP_3+CBMobile_2
flutter: 14:48:00.849160| [WS] verbose: Got response:
	HTTP/1.1 400 Bad Request
	Server: awselb/2.0
	Date: Wed, 07 Feb 2024 18:48:00 GMT
	Content-Type: text/html
	Content-Length: 220
	Connection: close
flutter: 14:48:00.849876| [WS] info: {BuiltInWebSocket#15} Got HTTP response (status 400)
flutter: 14:48:00.850153| [WS] error: {BuiltInWebSocket#15} WebSocket failed to connect! (reason=WebSocket/HTTP status 400)
flutter: 14:48:00.850345| [Sync] info: {Repl#14} Connection closed with WebSocket/HTTP status 400: "Bad Request" (state=1)
flutter: 14:48:00.850520| [Sync] error: {Repl#14} Got LiteCore error: WebSocket error 400, "Bad Request"
flutter: 14:48:00.850738| [Sync] verbose: {Repl#14} progress +0/+0, 0 docs -- now 0 / 0, 0 docs
flutter: 14:48:00.851250| [Sync] error: {C4Replicator#11} State: connecting, progress=0.00%, error=WebSocket error 400, "Bad Request"
flutter: 14:48:00.851627| [Sync] info: CBLReplicator status: connecting, progress=0/0, flag=2, error=6/400 (effective status=connecting, completed=0.00%, docs=0)
flutter: 14:48:00.852215| [Sync] info: {Puller#16}==> litecore::repl::Puller {Repl#14} @0x102568920
flutter: 14:48:00.852595| [Sync] verbose: {Puller#16} now stopped
flutter: 14:48:00.852756| [Sync] info: {Pusher#17}==> litecore::repl::Pusher {Repl#14} @0x102570980
flutter: 14:48:00.852895| [Sync] verbose: {Pusher#17} now stopped
flutter: 14:48:00.853210| [Sync] info: {Repl#14} now stopped
flutter: 14:48:00.853525| [Sync] info: BLIP sent 0 msgs (0 bytes), rcvd 0 msgs (0 bytes) in 0.330 sec. Max outbox depth was 0, avg nan
flutter: 14:48:00.853844| [DB] verbose: {DB#12} Housekeeping: 0 of 148 pages free (0%)
flutter: 14:48:00.854060| [DB] verbose: {DB#12} Closed SQLite database
flutter: 14:48:00.854266| [DB] info: {DB#12} Closing database
flutter: 14:48:00.854506| [DB] info: {CollectionImpl#13} Closed
flutter: 14:48:00.854693| [Sync] error: {C4Replicator#11} State: stopped, progress=0.00%, error=WebSocket error 400, "Bad Request"
flutter: 14:48:00.855005| [Sync] info: CBLReplicator status: stopped, progress=0/0, flag=2, error=6/400 (effective status=stopped, completed=0.00%, docs=0)

Happy to provide any additional info that might be necessary to help debug this.

**Comment by biozal** [comment]
Hey @PaulCapestany  - happy to try and help so your blip message is stating a bad request.  That's not good.  Any chance you can jump on Discord to maybe talk on chat about this?  I have several questions.

**Comment by biozal** [comment]
So I looked at your logs - a few things:

- App Services will require Secure Web Sockets (wss) instead of Web Sockets.  This means in your replicator_provider.dart file you would need to make sure your URL has the `wss` in it.  Your logs show ws but I think you might have scrubbed your logs and accidentally took out the WSS.  I'm assuming this but it's a good check.

- The screenshots are old from that tutorial.  Rather embarrassing that they haven't been fixed yet.  I'll ping the team that maintains these tutorials.

- Did you validate that your websocket URL works in your browser?  You can take off the wss part from Capella pop in https and put it in your web browser and you should at least get something back from that.   If you take off the endpoint and just browse to the raw URL you should get a JSON response that the app services is running, like a heartbeat message.

- The line about isClosed is trying to make sure that the replicator isn't currently running.  That is probably a bug.   I did it a lot differently in our Kotlin learning path where I calculated the state and then stored it in a var that I could use in other methods (functions).   The Kotlin learning path is probably a better way to do it, so I'll need to update this to use that methodology:  https://github.com/couchbase-examples/android-kotlin-cbl-learning-path/blob/main/src/app/src/main/java/com/couchbase/learningpath/services/ReplicatorServiceDb.kt#L92

**Comment by biozal** [comment]
I've updated the comments and pushed out some code changes to help with this process.

**Comment by PaulCapestany** [comment]
Thanks again @biozal for taking the time to chat/debug with me yesterday! Was able to get things syncing, and with all your latest commits I think it's a lot more clear how to get replication working with Capella—much appreciated :)
